### ISSUE TITLE
Bundle plugin into a VS Code extension

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/typescript-styled-plugin#10]
We have an experimental means for a VS Code extension to contribute TypeScript plugins. This would have a few benefits:

1. Simplified installation
1. No `jsconfig` or `tsconfig` configuration required.
1. No need to npm install the plugin into each workspace or put it in your `package.json`
1. Will work with loose js/ts files (files that are not part of any js/tsconfig project)
1. Extension can also contribute other goodness, such as syntax highlighting

To be clear, the TypeScript server plugin itself would continue to work across all editors that use the TypeScript  language service. This issue merely tracks bundling up the plugin into a VS Code extension

**Comment by mjbvz** [comment]
Here's a prototype: https://github.com/mjbvz/vscode-styled-components-extension

Requires a build of VS Code with https://github.com/Microsoft/vscode/commit/1bfad134b03215d91ab84f913814050946f41f2a

**Comment by mxstbr** [comment]
Yeeessss! Shall we merge this with https://github.com/styled-components/vscode-styled-components?

**Comment by deadcoder0904** [comment]
Any updates ❓

**Comment by mjbvz** [comment]
https://github.com/styled-components/vscode-styled-components/pull/41

**Comment by mjbvz** [comment]
Fixed by https://github.com/styled-components/vscode-styled-components/pull/41
