### ISSUE TITLE
No syntax highlighting when styled has second argument

### ISSUE THREAD

**Issue by brandonkal** [microsoft/typescript-styled-plugin#101]
The syntax highlighting does not function when styled has a second argument:
```jsx
const El = styled('div', options)`
    color: blue; /* This is not highlighted, though ts-styled-plugin still works */
`
```
The highlighting should occur regardless of the count of arguments provided to styled().

**Comment by kobber** [comment]
This also seems to be the case when using Typescript generic types:
```typescript
const Button = styled.button<{
  color: string;
}>`
  display: inline-block; /* does not get highlighted */
`
```

**Comment by brandonkal** [comment]
My editor provides syntax highlighting for your example and I've never had an issue with highlighting when using type arguments.

**Comment by Arynaine** [comment]
I can second this. Though, funny enough, if you pull the code into the same line, highlighting works. In multi-line, it breaks. Let me give you an example;

This get highlighting and intellisense;
`const StyledWrapper = styled.main<{header: boolean, footer: boolean, backgroundColor: Color }>`
       ...myStyles
`;
`

This doesnt;
`
const StyledWrapper = styled.main<{
  header: boolean;
  footer: boolean;
  backgroundColor: Color;
}>`
 ...myStyles
`;
`

**Comment by mjbvz** [comment]
This  repo/library does not provide syntax highlighting. Please file this again https://github.com/styled-components/vscode-styled-components
