### ISSUE TITLE
Suggestions and hovers still do not work in Atom?

### ISSUE THREAD

**Issue by webMasterMrBin** [microsoft/typescript-styled-plugin#104]
i see this https://github.com/microsoft/typescript-styled-plugin/issues/3
this is a atom-typescript problem?

i can see error report, but no autocomplete

![2019-06-30 11 38 03](https://user-images.githubusercontent.com/25171709/60391887-99ef3300-9b2b-11e9-9ed5-83626dd5ff61.gif)

atom-typescript: v13.2.1
typescript-style-plugin: v0.14.0

**Comment by mjbvz** [comment]
Same upstream issue as #3: https://github.com/TypeStrong/atom-typescript/issues/1351
