### ISSUE TITLE
False positive identifier expected pseudo selector on interpolated class names

### ISSUE THREAD

**Issue by brandonkal** [microsoft/typescript-styled-plugin#105]
Take this css:
```js
const rateDisabled = css`
  .${rateCls}:not(&) .${star}:hover ~ .${star} {
/* ^ ident expected   ^ ident expected */
    color: ${starWhite};
  }
`
```
The types of rateCls and star are strings. This plugin throws these false positives as it doesn't understand there is a string between the period and the :not().

Also, there should be some way to ignore these errors, just as we can // @ts-ignore when Typescript itself makes bad inferences.

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
