### ISSUE TITLE
Support css<Props>`` like element<Props>``

### ISSUE THREAD

**Issue by iansan5653** [microsoft/typescript-styled-plugin#106]
The styled-components `css` tag passes props through from the parent element, so something like:
```tsx
interface Props {
  //...
}
const baseHeadingStyles = css<Props>`
  //...
`;
```
is perfectly valid. This doesn't get recognized by the extension though.

**Comment by ctretyak** [comment]
+1

**Comment by lucastobrazil** [comment]
Agree here!

**Comment by iansan5653** [comment]
@mjbvz I'm willing to submit a PR. Can you show me where in the code to look for this?

**Comment by mjbvz** [comment]
What isn't working? The highlighting?

<img width="631" alt="Screen Shot 2020-01-27 at 11 51 27 AM" src="https://user-images.githubusercontent.com/12821956/73208486-62fdf180-40fb-11ea-9032-1f4608f6a02f.png">

This plugin doesn't provide the highlighting. That comes from https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components

**Comment by iansan5653** [comment]
Yeah this is about the highlighting.
