### ISSUE TITLE
`property value expected` with &:pseudo-selector

### ISSUE THREAD

**Issue by cubeghost** [microsoft/typescript-styled-plugin#108]
👋 getting `[ts-styled-plugin] property value expected` when using a & and a pseudo selector. was also getting it earlier with `${OtherStyledComponent}:hover & {}` but that error disappeared

<img width="378" alt="Screen Shot 2019-10-18 at 2 18 29 PM" src="https://user-images.githubusercontent.com/1895116/67118762-91db0200-f1b3-11e9-887f-d3149f0adcad.png">
 
```js
const Item = styled.li`
  counter-increment: ranking;
  padding: ${p => p.theme.spacing.full};
  padding-left: 0;
  position: relative;

  &:not(:last-child) {
    border-bottom: 1px solid #000;
  }
`;
```

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
