### ISSUE TITLE
not work in sublime text 3

### ISSUE THREAD

**Issue by iahu** [microsoft/typescript-styled-plugin#109]
Version info

- Sublime Text: 3.2.2
- TypeScript: 3.7.4

![image](https://user-images.githubusercontent.com/1704588/71570011-f00a5680-2b0d-11ea-8891-ccf6cc12bea5.png)

**Comment by mjbvz** [comment]
This plugin does not provide highlighting, only intellisense. What isn't working?

**Comment by iahu** [comment]
no intellisense feature, no hover tips

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
