### ISSUE TITLE
Typescript Types or Emotionjs adding Label to Styled break color highlighting

### ISSUE THREAD

**Issue by Sensiblemnd** [microsoft/typescript-styled-plugin#111]
![styledComponents3](https://user-images.githubusercontent.com/940303/73707953-f5d5f780-46ca-11ea-9317-88d8c2ffb277.PNG)
![styledComponents](https://user-images.githubusercontent.com/940303/73707866-adb6d500-46ca-11ea-97a2-3907a6fa4aa3.PNG)
![styledComponents2](https://user-images.githubusercontent.com/940303/73707867-adb6d500-46ca-11ea-90b7-d80b435567a6.PNG)

**Comment by mjbvz** [comment]
This extension does not provide syntax coloring. You're looking for https://github.com/styled-components/vscode-styled-components
