### ISSUE TITLE
Unknown property: 'speak'

### ISSUE THREAD

**Issue by devalnor** [microsoft/typescript-styled-plugin#112]
css attribute 'speak' is unknown.

References:
https://www.w3.org/TR/2018/NOTE-css3-speech-20180605/
https://www.w3schools.com/cssref/css_ref_aural.asp
https://www.cssportal.com/css-properties/speak.php
https://caniuse.com/#feat=speech-recognition

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
