### ISSUE TITLE
CSS validation doesn’t work inside @media rules

### ISSUE THREAD

**Issue by sunknudsen** [microsoft/typescript-styled-plugin#113]
I use the [vscode-styled-components](https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components) plugin which [relies](https://github.com/styled-components/vscode-styled-components/pull/41) on typescript-styled-plugin.

In the following example, the first `foo: 40px;` throws a validation error, but not the second. Is this a known limitation or a bug?

```shell
Unknown property: 'foo'ts-styled-plugin(9999)
```

```typescript
const Test = styled.div`
  foo: 40px;
  @media screen and (min-width: 640px) {
    foo: 40px;
  }
`
```

![Screen Shot 2020-03-30 at 10 14 30 AM](https://user-images.githubusercontent.com/2117655/77922895-aac20600-726f-11ea-89cd-2f74e3903d91.png)

**Comment by kkkasio** [comment]
I have the same problem.
whenever I write in a media query, auto complete does not work!

![compete](https://user-images.githubusercontent.com/19254402/99212384-ab30f200-27a9-11eb-990e-30e3f4d6f611.png)
Following the documentation write inside the CSS tag  [https://github.com/Microsoft/typescript-styled-plugin#tags](https://github.com/Microsoft/typescript-styled-plugin#tags)

![no complete](https://user-images.githubusercontent.com/19254402/99212549-111d7980-27aa-11eb-8a7d-d18ba913e8bd.png)
however, when I write inside a media, nothing works!

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
