### ISSUE TITLE
Autocomplete without colon and semicolon

### ISSUE THREAD

**Issue by dilincoln** [microsoft/typescript-styled-plugin#114]
With the **VS Code Styled Components extension** the editor do not insert colon and semicolon on CSS proprety/attributes, see in the gif above:

**in CSS files:**

![css_file](https://user-images.githubusercontent.com/37885454/79081625-9d882b00-7cf5-11ea-80c2-73119ce7ad26.gif)

**in JS files:**
![js_file](https://user-images.githubusercontent.com/37885454/79081634-a973ed00-7cf5-11ea-8a78-c4b398bf99fa.gif)

How can i enable this autocomplete feature?

**Comment by michaelschufi** [comment]
What I also would like to see is the value suggestions triggered automatically. BTW: I have filed an issue in the [styled-components extension repo](https://github.com/styled-components/vscode-styled-components/issues/220) as well, so maybe that could be an option soon.

**Comment by pxlla** [comment]
I just installed and for a time colons were inserted properly after new values were added, however after I re-started VS Code with a new session, colons needed to be added manually every time. Not a dealbreaker but a pain nonetheless.

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
