### ISSUE TITLE
Unknown property: dominant-baseline in svg texts

### ISSUE THREAD

**Issue by pguijarr** [microsoft/typescript-styled-plugin#115]
## System:
 - OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
 - CPU: (2) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
 - Memory: 881.58 MB / 7.79 GB
 - Container: Yes
 - Shell: 3.1.2 - /usr/bin/fish
## Binaries:
 - Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
 - Yarn: 1.19.1 - ~/.nvm/versions/node/v12.13.0/bin/yarn
 - npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
## npmPackages:
 - styled-components: ^5.1.0 => 5.1.0

## Reproduction

![image](https://user-images.githubusercontent.com/57676540/82143379-b9767380-9843-11ea-8571-ff87e2bcae1f.png)

## Expected Behavior
Property should be found 
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dominant-baseline
## Actual Behavior
![image](https://user-images.githubusercontent.com/57676540/82143379-b9767380-9843-11ea-8571-ff87e2bcae1f.png)

**Comment by natevw** [comment]
The https://github.com/microsoft/vscode-css-languageservice project closed **their** underlying ticket for some reason, but afaict there's nothing this plugin really could/would do other than wait for the css-languageservice to add information about this CSS property.

**Comment by natevw** [comment]
Looks like https://github.com/microsoft/vscode/issues/85828 might be the ticket to watch for any movement here.

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
