### ISSUE TITLE
} expected, at-rule or selector expected on valid styled component

### ISSUE THREAD

**Issue by davesteinberg** [microsoft/typescript-styled-plugin#116]
I'm getting errors on a styled component that seems valid to me:

```
const sizeProp = ({ align }) => (align ? "width" : "height");
const sizeValue = ({ size }) => (size === "sm" ? "16px" : "20px");

export const Icon = styled.img`
  height: ${sizeValue};
  ${sizeProp}: 16px;
  ${sizeProp}: ${sizeValue};
`;
```

I see **ts-styled-plugin(9999)** errors on the last two lines:

- **} expected** on the first `$` in the second-last line
- **at-rule or selector expected** on the `;` in the last line

The previous two lines are fine. They're just there to illustrate that it's okay when I have a computed property or value, but the combination of both seem to confuse the plugin.

**Comment by finnmerlett** [comment]
I can corroborate this:

The same issue occurs for me when using a variable as an attribute name and a property value. In my situation the variable is actually const-string-typed, and both of the potential values are valid attribute names.

![Screenshot 2023-02-27 at 12 25 16](https://user-images.githubusercontent.com/49064567/221563330-8e0a9d8e-63e0-4394-907c-e09ec35357d1.png)
![Screenshot 2023-02-27 at 12 25 37](https://user-images.githubusercontent.com/49064567/221563405-5459dc17-6218-4f22-a78b-d7d52bae14ee.png)

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
