### ISSUE TITLE
It is not working when use `export default`.

### ISSUE THREAD

**Issue by SidKwok** [Microsoft/typescript-styled-plugin#12]
It works just fine when:
```javascript
import styled from 'styled-components'

const Button = styled.a`
    color: blue;
`

export default Button;
```

But when it comes to:
```javascript
import styled from 'styled-components'

export default styled.a`
    color: blue;
`;
```

The plugin seems not working at this time.

ts: 2.5.3
vscode: 1.16.1

**Comment by mjbvz** [comment]
What issues are you seeing? I see intellisense and error reporting working just fine in both cases with 0.0.5

**Comment by SidKwok** [comment]
My bad. It went well this time.
