### ISSUE TITLE
How to debug this plugin when launching extension?

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/typescript-styled-plugin#120]
Does anyone know how to debug this plugin?
I'm looking into add the color selector, but it seems its not bundled with the extension and used some other way.

I can run the e2e tests, but i want to run this through the debugger while vscode-styled-components is active.

Part of https://github.com/styled-components/vscode-styled-components/issues/95

**Comment by jasonwilliams** [comment]
I found this https://github.com/microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin#testing-locally

**Comment by mjbvz** [comment]
You need to attach to the TypeScript server to debug through the plugin. To do this:

- Set an environment variable `TSS_DEBUG=PORT` (for example `TSS_DEBUG=9999`)
- Start the typescript server in an environment that has `TSS_DEBUG` set
- Then attach to port 9999 from chrome or using VS Code's debugging tools

You can also use `TSS_DEBUG_BRK` to make the remain paused until you connect to it
