### ISSUE TITLE
How to add getColorPresentations to styled-plugin for the color picker

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/typescript-styled-plugin#122]
Hey @mjbvz !

I've been poking around this plugin and the CSS language service to try and see how i can fix https://github.com/styled-components/vscode-styled-components/issues/95

It seems i need to support `getColorPresentations ` like here:
https://github.com/microsoft/vscode-css-languageservice/blob/master/src/cssLanguageService.ts#L63

But I don't think that method is available in `typescript-styled-plugin` as it extends https://github.com/microsoft/typescript-template-language-service-decorator/blob/master/src/template-language-service.ts#L9-L74 which doesn't cover that.

Do you have any suggestions?

Hovering over a color in a css file triggers the request
```
[Trace - 21:36:54] Sending request 'textDocument/colorPresentation - (13)'.
Params: {
    "color": {
        "red": 0,
        "green": 0,
        "blue": 0,
        "alpha": 1
    },
    "textDocument": {
        "uri": "file:///c%3A/Users/jasew/workspace/testing/test.css"
    },
    "range": {
        "start": {
            "line": 1,
            "character": 9
        },
        "end": {
            "line": 1,
            "character": 13
        }
    }
}


[Trace - 21:36:54] Received response 'textDocument/colorPresentation - (13)' in 2ms.
Result: [
    {
        "label": "rgb(0, 0, 0)",
        "textEdit": {
            "range": {
                "start": {
                    "line": 1,
                    "character": 9
                },
                "end": {
                    "line": 1,
                    "character": 13
                }
            },
            "newText": "rgb(0, 0, 0)"
        }
    },
    {
        "label": "#000000",
        "textEdit": {
            "range": {
                "start": {
                    "line": 1,
                    "character": 9
                },
                "end": {
                    "line": 1,
                    "character": 13
                }
            },
            "newText": "#000000"
        }
    },
    {
        "label": "hsl(0, 0%, 0%)",
        "textEdit": {
            "range": {
                "start": {
                    "line": 1,
                    "character": 9
                },
                "end": {
                    "line": 1,
                    "character": 13
                }
            },
            "newText": "hsl(0, 0%, 0%)"
        }
    }
]
```

**Comment by mjbvz** [comment]
Unfortunately I think this may not be possible. This plugin runs inside the TypeScript server, so it can only communicate with VS Code using the standard TypeScript apis. There is no equivalent of `colorPresentation` in typescript, so I don't know how you'd pass the color info back to VS Code 

You may have to handle this in the styled-components extension itself since that can use the VS Code apis directly

**Comment by jasonwilliams** [comment]
@mjbvz does this mean we’ll need to create another language server? Because colorpresentation can only be set as a language service response and not directly in a plugin.

**Comment by mjbvz** [comment]
Instead of a full language server, you can also use the VS Code apis directly. Take a look at `DocumentColorProvider`: https://github.com/microsoft/vscode/blob/0579e831389c977e3f51981b8b59f524f510df89/src/vs/vscode.d.ts#L4224

**Comment by jasonwilliams** [comment]
Thanks @mjbvz  i think this can be closed now
