### ISSUE TITLE
svg css properties don't work

### ISSUE THREAD

**Issue by lifeiscontent** [microsoft/typescript-styled-plugin#123]
as noted by https://www.w3.org/TR/SVG/styling.html

properties like this should not be considered invalid:

```jsx
export const Circle = styled.circle`
  cx: 18;
  cy: 18;
  r: 16;
`;
```

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
