### ISSUE TITLE
Support CSS Module `composes` property

### ISSUE THREAD

**Issue by jsg2021** [microsoft/typescript-styled-plugin#124]
When I use `composes` in a styled component this extension warns about the unsupported property, when it works perfectly fine.

```
Unknown property: 'composes' ts-styled-plugin(9999)
```

I'm not using ts on my project so adding something to a tsconfig is not ideal. maybe a vscode option?

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
