### ISSUE TITLE
The CSS `color-scheme` property shouldn’t be unknown

### ISSUE THREAD

**Issue by jaydenseric** [microsoft/typescript-styled-plugin#125]
The CSS `color-scheme` property is incorrectly reported by this plugin as being unknown:

<img width="567" alt="Screen Shot 2020-11-16 at 1 51 03 pm" src="https://user-images.githubusercontent.com/1754873/99208175-e536de00-2813-11eb-9343-2c7cef4932f2.png">

In fact, this is a standard CSS property:

- https://www.w3.org/TR/css-color-adjust-1/#propdef-color-scheme
- https://web.dev/color-scheme/#the-color-scheme-css-property

**Comment by jaydenseric** [comment]
After digging around some more, it seems this is related:

https://github.com/microsoft/vscode-css-languageservice/issues/223

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
