### ISSUE TITLE
CSS linting breaks if in css props as template literal 

### ISSUE THREAD

**Issue by omonk** [microsoft/typescript-styled-plugin#126]
When defining a styled component the plugin enables syntax highlighting **and** CSS linting in the styled.el`` definition. When writing inline css in a styled component via the `css` prop the plugin enables syntax highlighting but does not enforce css linting.

```javascript
const Comp1 = styled.div`
  notaprop: foo;
`;

const Comp2 = (props) => (
  <div
    css={`
      alsonotaprop: foo;
    `}
  >
    {props.children}
  </div>
);
```

![image](https://user-images.githubusercontent.com/7108120/99652718-14399380-2a50-11eb-9c3f-18e49949adcc.png)

I know a small amount about TM Scopes and these two lines seem to point to the same scope... 

![image](https://user-images.githubusercontent.com/7108120/99652826-392e0680-2a50-11eb-88ad-1e9fc9900cbb.png)
![image](https://user-images.githubusercontent.com/7108120/99652836-3b906080-2a50-11eb-8747-941a76d31fec.png)

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
