### ISSUE TITLE
TSC compiles with ignoring lint errors

### ISSUE THREAD

**Issue by just0110** [microsoft/typescript-styled-plugin#127]
After all configurations, i'm expected that `tsc` compiling would failed. Especially in pipelines.
`tsc` doesn’t show me any errors or warnings in console, unlike code at all.
Is this package only for visual error reporting?

![Screenshot 2020-12-23 at 17 31 01](https://user-images.githubusercontent.com/13615232/103012838-d5ae6180-4544-11eb-99ea-faaba76f7904.png)

**Comment by mjbvz** [comment]
Plugins are only used for language tooling such as IntelliSense. They are not loaded during compile with tsc
