### ISSUE TITLE
How to use "Preferances" Property In "emmet" configs 

### ISSUE THREAD

**Issue by abdalla-alHosainy** [microsoft/typescript-styled-plugin#133]
I want to make "emmet" fuzzy abbreviations appear in the first suggestion || or || disable suggestion to be able to use the  { TAB } button directly to expand "emmet" abbreviations

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
