### ISSUE TITLE
.vue file in vscode

### ISSUE THREAD

**Issue by u-rogel** [microsoft/typescript-styled-plugin#135]
I am trying to use the `vscode-styled-components` extension with vscode in a VueJs project.

I get syntax highlighting but not auto-completion.
I checked my project and I can get it to run with a normal `.js` file but not in a `.vue` file.

Any guidance on how to solve it?

**Comment by mjbvz** [comment]
Please file this against the Vue extension. It uses its own copy of the TypeScript server which would also need to load this plugin
