### ISSUE TITLE
Support for monaco editor

### ISSUE THREAD

**Issue by rob-myers** [microsoft/typescript-styled-plugin#140]
There seems to be a lack of css-in-js syntax highlighting support for web-based editors.

So far, the only solution I know is to create a custom CodeMirror mode, which [integrates a `TemplateTokenizer`](https://github.com/codemirror/google-modes/blob/master/src/javascript.js) from the `codemirror/google-modes` repo.

I'd prefer to use your plugin somehow with monaco-editor, but is that even possible (modulo a refactor)?

**Comment by mjbvz** [comment]
This is out of scope for this project. However you can see if you can get Monaco's built-in TS support to load language service plugins like this
