### ISSUE TITLE
[Regression] - Virtual Document Provider hasn't compiled correctly causing failure in extension

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/typescript-styled-plugin#143]
Hi @mjbvz 

We had an [issue](https://github.com/styled-components/vscode-styled-components/issues/317) in our latest release of VSCode Styled Component which is the first version to use v0.18 of this plugin.

Keyframes is not working.
![Screenshot from 2021-07-26 12-41-58](https://user-images.githubusercontent.com/5755214/126960540-01a289e8-f25b-45dd-9e3d-20526e47fd0c.png)
![Screenshot from 2021-07-26 12-42-00](https://user-images.githubusercontent.com/5755214/126960548-6fad293c-7d4f-4f00-aa54-0d8abd382e2d.png)

After investigation i can see that testing directly against `main` works, so there must have been an issue when this plugin was published.

Taking a look at the published version `:keyframes` is missing.  (line 49 only has :root)
https://unpkg.com/browse/typescript-styled-plugin@0.18.0/lib/_virtual-document-provider.js
The above file should match up with:
https://gist.github.com/jasonwilliams/0179d3b4dad10ed25f3fec118805c177 

It looks like none of the changes made here have been compiled:
https://github.com/microsoft/typescript-styled-plugin/blob/main/src/_virtual-document-provider.ts

Are you able to help?

**Comment by jasonwilliams** [comment]
Pings @mjbvz

**Comment by mjbvz** [comment]
Just published 0.18.1 with your emmet fix. I believe it should also now include the previous change: 

https://unpkg.com/browse/typescript-styled-plugin@0.18.1/lib/_virtual-document-provider.js

Let me know if you are still seeing any issues
