### ISSUE TITLE
vector-effect not recognized

### ISSUE THREAD

**Issue by Akkuma** [microsoft/typescript-styled-plugin#144]
`Unknown property: 'vector-effect' ts-styled-plugin(9999)'`

**Comment by jasonwilliams** [comment]
Please see https://github.com/styled-components/vscode-styled-components#i-get-unknown-property-x-on-a-property-i-know-is-valid

**Comment by btonasse** [comment]
> Please see https://github.com/styled-components/vscode-styled-components#i-get-unknown-property-x-on-a-property-i-know-is-valid

This extension does not solve this issue. I have it installed and I'm still getting this warning.

**Comment by btonasse** [comment]
I don't understand this suggestion. vector-effect is a standard property which is in MDN

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
