### ISSUE TITLE
Getting `} expectedts-styled-plugin(9999)` with `vscode-styled-components`

### ISSUE THREAD

**Issue by jackpeplinski** [microsoft/typescript-styled-plugin#146]
I'm using `vscode-styled-components` and I get the following error on all my style component CSS. This is similar to #136 I think.

![Screen Shot 2021-08-22 at 11 39 26 PM](https://user-images.githubusercontent.com/30737750/130386907-a307acda-965c-4b9c-8c75-d43b54ecdcdf.png)
![Screen Shot 2021-08-22 at 11 39 42 PM](https://user-images.githubusercontent.com/30737750/130386931-9cb56aea-6a72-4c92-8dea-38faf1e2cc94.png)

**Comment by 5tormTrooper** [comment]
Same here, but only when using keyframes.
![Image 2021-09-28 at 5 31 27 PM](https://user-images.githubusercontent.com/4154407/135118711-4e635604-de02-44d4-bb72-c4541b74caca.jpg)

Running v1.6.6

**Comment by jorenbroekema** [comment]
```js
export const coolGray50 = css`#F9FAFB`;
```
This produces the problem too. These literals don't have to contain valid CSS, because they can be imported/exported as parts and then applied to other literals. So in my opinion, the plugin should take into account that you can nest tagged template literals and be less harsh on the errors if they're not valid syntax by themselves.

**Comment by hscheuerle** [comment]
if it's not valid css just use a string instead of css

**Comment by finnmerlett** [comment]
Although @jackpeplinski I think your issue might actually be that you've got incorrect curly braces inside your backticks. The other issues in the comments seem valid though.

**Comment by finnmerlett** [comment]
@5tormTrooper if you are just going to put it inline anyway, you can remove the nested `` css`...` `` and just put your string-literal interpolations in the line like this:

```css
slideInLeft: ${slideLeft} 200ms cubic-bezier(0.250, 0.460, 0.940) both;
```

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
