### ISSUE TITLE
ts-styled-plugin(9999)

### ISSUE THREAD

**Issue by JohnathanHuggett** [microsoft/typescript-styled-plugin#147]
Im seeing this error whenever I try to interpolate a css property.

![Screen Shot 2021-08-24 at 12 33 16 PM](https://user-images.githubusercontent.com/33938478/130655096-64c435ee-d1d6-4f2c-a0d9-e945ca38f58e.png)
![Screen Shot 2021-08-24 at 12 33 35 PM](https://user-images.githubusercontent.com/33938478/130655105-481b4af8-283e-403d-8b38-45c7f9040b5e.png)

**Comment by skmohammadi** [comment]
I have same problem

**Comment by AlonBru** [comment]
Assuming you use vscode, try pressing `ctrl+shift+p` and then running the `TypeScript: Restart TS Server` command.
Seems to work for me.

**Comment by mattbrannon** [comment]
Same problem. Restarting TS Server didn't help.

**Comment by Justin9606** [comment]
I solved it by creating the jconfig.json inside the root of my project and adding:

***if  your project is in Typescript then create tsconfig.json****

{
  "compilerOptions": {
    "plugins": [
      {
        "name": "typescript-styled-plugin",
        "lint": {
          "validProperties": [
            "margin-vertical",
            "margin-horizontal",
            "padding-vertical",
            "padding-horizontal",
            "shadow-color",
            "shadow-opacity",
            "shadow-radius",
            "elevation"
          ]
        }
      }
    ]
  }
}

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
