### ISSUE TITLE
Unknown property: accent-color

### ISSUE THREAD

**Issue by mtmeyer** [microsoft/typescript-styled-plugin#148]
`accent-color` doesn't seem to be supported in the plugin.  As far as I know it's valid CSS, and a recent addition to the language.

![image](https://user-images.githubusercontent.com/9434150/133263381-815918fa-116a-4713-9f0c-cd5d2e4b0bb2.png)

https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
