### ISSUE TITLE
IntelliSense for new CSS property names and values

### ISSUE THREAD

**Issue by mahdi-sheibak** [microsoft/typescript-styled-plugin#149]
hi I'm using styled components in react native 

tsconfig.json

```
"plugins": [
      {
        "name": "typescript-styled-plugin",
        "lint": {
          "validProperties": [
            "aspect-ratio",
            "elevation",
            "margin-vertical",
            "margin-horizontal",
            "padding-horizontal",
            "padding-vertical",
            "resize-mode",
            "shadow-color",
            "shadow-opacity",
            "shadow-offset",
            "shadow-radius",
            "text-align-vertical",
            "tint-color"
          ]
        }
      }
    ]

```
but not give me IntelliSense code for new specific properties

example: 
   aspect-ratio
   elevation
   margin-vertical
   margin-horizontal
   padding-horizontal
   padding-vertical
   resize-mode
   shadow-color
   shadow-opacity 
   shadow-offset 
   shadow-radius
   text-align-vertical
   tint-color

**Comment by karlhorky** [comment]
Seems like at least some of these would be resolved by running `npm run update-data` in `vscode-css-languageservice`, as mentioned here:

- https://github.com/microsoft/vscode-css-languageservice/pull/317#issuecomment-1323324439

**Comment by karlhorky** [comment]
Now that https://github.com/microsoft/vscode-css-languageservice/pull/319 is merged, maybe this new version `6.2.1` will trickle in to `typescript-styled-plugin` at some point!

**Comment by jasonwilliams** [comment]
@karlhorky are you on the styled components discord? Could you ping me there if so

**Comment by jasonwilliams** [comment]
So basically this repo isn't maintained by Microsoft anymore and needs to be forked and moved into the @styled organization. We should also update the dependencies while we're at it. 

I don't have much time these days and don't know when i would get around to doing it. But that is the task. 
As there's many issues cropping up about this issue I will try to see what I can do.

Once done i will need some people to test the changes have worked. I will also try to link this issue once we've migrated

**Comment by karlhorky** [comment]
Ok great, I can probably devote a bit of time to testing extension updates  👍

**Comment by karlhorky** [comment]
Ok great, are @probablyup or other Styled Components maintainers available to help with any of this migration? Maybe even Emotion maintainers like @emmatown or @Andarist would be able to lend a hand, since this tooling also directly benefits Emotion users.

I can probably devote a bit of time to testing extension updates  👍

**Comment by jasonwilliams** [comment]
There's a pre-release version here https://marketplace.visualstudio.com/items?itemName=styled-components.vscode-styled-components 1.7.6

**Comment by karlhorky** [comment]
Ok, I'll test this, and reply with my feedback in this PR (at least this looks like the correct place 🤔):

- https://github.com/styled-components/typescript-styled-plugin/pull/2

**Comment by karlhorky** [comment]
Ran into the problem with a different CSS property just now - [`accent-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color) doesn't appear to work, in either the normal `styled-components.vscode-styled-components@1.7.5` Release version or the `styled-components.vscode-styled-components@1.7.6` Pre-Release version (see below).

Maybe the property is too new and not yet in the `vscode-css-languageservice` data?

The error message is "Unknown property: 'accent-color".

<img width="728" alt="Screenshot 2022-12-14 at 16 39 17" src="https://user-images.githubusercontent.com/1935696/207640996-10299756-6279-4794-bf7b-35c010b58474.png">

<img width="815" alt="Screenshot 2022-12-14 at 16 38 50" src="https://user-images.githubusercontent.com/1935696/207641042-6ae0f9b1-9cb6-4bf8-8c42-e0a0ee640ea6.png">

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
