### ISSUE TITLE
Autocomplete Custom Properties

### ISSUE THREAD

**Issue by marti6jm** [microsoft/typescript-styled-plugin#152]
Is it possible in anyway, or as a future feature, for this plugin to support autocompleting custom properties/css variables? Possibly based on a variable file passed through a setting or something?

**Comment by alexgwolff** [comment]
+1

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
