### ISSUE TITLE
`emmet.showExpandedAbbreviation: never` doesn't disable Emmet abbreviation autocomplete

### ISSUE THREAD

**Issue by karlhorky** [microsoft/typescript-styled-plugin#154]
Hi there, first of all, thanks for this plugin! Very nice to have CSS features in JS/TS 🙌

I am using this plugin via the `vscode-styled-components` extension (styled-components/vscode-styled-components#57 introduced Emmet into this extension)

However, I do not want to use Emmet at all. I don't mind if it would just appear and not break my workflow, but it causes some very strange things to happen when typing `h1, h2, h3` within a `css` tagged template literal:

https://user-images.githubusercontent.com/1935696/141528952-9e2d7e3f-1b6b-4898-b487-2e690683a044.mp4

Apparently it should possible to disable Emmet with the settings below (which should work according to [the VS Code docs](https://code.visualstudio.com/docs/editor/emmet#_disable-emmet-in-suggestions) and  [the `typescript-styled-plugin` docs](https://github.com/microsoft/typescript-styled-plugin#showexpandedabbreviation))

```json
  "emmet.showExpandedAbbreviation": "never",
```

However, this doesn't work.

The only way to disable this is with the following settings, which also disables other suggestions:

```json
  "editor.quickSuggestions": {
    "other": false
  }
```

---

Originally reported over at https://github.com/styled-components/vscode-styled-components/issues/331

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
