### ISSUE TITLE
) expected , { expected (9999) when using @supports not ( not backdrop-filter : blur(10px)) { }

### ISSUE THREAD

**Issue by amandeepmicro** [microsoft/typescript-styled-plugin#158]
Hey , 

I'm getting error messages with the following syntaxes using 

```
@supports not ( not backdrop-filter : blur(10px)) {  

}
```
whereas it works for other syntaxes 
```
@supports not (not display:grid) {

  }
```

![image](https://user-images.githubusercontent.com/55043082/144738495-aa0fe2eb-e02c-4801-876d-f208af99a53a.png)

Please see this problem. Thank you

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
