### ISSUE TITLE
semi-colon expected when using props in "${...}" - ts-styled-plugin(9999)

### ISSUE THREAD

**Issue by aderchox** [microsoft/typescript-styled-plugin#162]
The code below is apparently correct and works fine too, but I can't get rid of this typescript error even with ts-expect-error and ts-ignore:
```
const StyledNotificationItem = styled.div<Partial<INotificationItemProps>>`
  //...
  & .notification__linktext {
    //...
    &::after {
      content: "${(props) => {
        if (props.direction === "ltr") {
          return " 🡵";
        } else {
          return " 🡴";
        }
      }}"; // <--- HERE: The error is: "semi-colon expected. ts-styled-plugin(9999)"
    }
  }
`;
```

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
