### ISSUE TITLE
Update dependency from `vscode-emmet-helper` to `@vscode/emmet-helper`.

### ISSUE THREAD

**Issue by arthwood** [microsoft/typescript-styled-plugin#163]
As per warning:

> warning typescript-styled-plugin > vscode-emmet-helper@2.6.4: This package has been renamed to @vscode/emmet-helper, please update to the new name

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
