### ISSUE TITLE
How to avoid ts-styled-plugin(9999) when i am not even using styled components and don't have the plugin installed anywhere?

### ISSUE THREAD

**Issue by gotjoshua** [microsoft/typescript-styled-plugin#165]
any help?

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
