### ISSUE TITLE
Support suppression/ignore comments

### ISSUE THREAD

**Issue by leoselig** [microsoft/typescript-styled-plugin#169]
This is what #70 already asked for. No reasoning was ever provided as to why it would be "out of scope" so I'm hoping to either put this on the agenda or get some insight as to why it shouldn't be there.

Generally, I believe this is a viable feature requests since there tend to always be rules that really provide  true positives in 99% of the cases but I still want to opt out sometimes. Existing linters seem to agree on that and all have implemented some variant of line/block-based suppression.

Thanks for providing some context!

**Comment by finnmerlett** [comment]
I also think this would be a good addition. There are several places within my codebase where the code is valid but the linter trips up. Whilst waiting for these to be fixed, a `disable-line` or `disable-block` comment would be extremely useful to clear away irritating false errors.

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
