### ISSUE TITLE
Unknown property: 'y'ts-styled-plugin(9999)

### ISSUE THREAD

**Issue by waterhumanB** [microsoft/typescript-styled-plugin#174]
![styled-Y](https://user-images.githubusercontent.com/69314161/214185373-39ba9fc6-2516-4203-8d89-505a03c10b59.png)

When styling with a styled component, you cannot use the y attribute inside a rect tag in an svg tag. Any workaround?

Or should I use the y attribute on the rect tag?

**Comment by finnmerlett** [comment]
It appears that `y` is not defined as a valid attribute name. I believe you can change this as described here https://github.com/microsoft/typescript-styled-plugin/issues/147#issuecomment-1081424487

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)
