### ISSUE TITLE
Working example setup

### ISSUE THREAD

**Issue by thymikee** [Microsoft/typescript-styled-plugin#19]
I've tried to set this plugin with VS Code in my project, but couldn't make it for whatever reasons, wondering if that's a bug or I'm doing something wrong. 

Having an example app set up in this repo (unless we get the VS Code extension #10) would definitely be helpful in such cases.

Thanks!

**Comment by mjbvz** [comment]
I've created  https://github.com/mjbvz/typescript-styled-plugin-example-project to show how to use this plugin with JavaScript. Tested in VSCode 1.17 and 1.18 insiders 

Let me know if you still can't get this to work properly
