### ISSUE TITLE
Breaks autoimports with TS 2.6.2

### ISSUE THREAD

**Issue by asvetliakov** [Microsoft/typescript-styled-plugin#24]
```typescript-styled-plugin 0.2.1```
See https://github.com/Microsoft/TypeScript/issues/20304

Repro:
1. Install ```@types/react-router-dom```
2. Enable plugin in tsconfig.json
3. Type ```Link``` in some file

**Comment by mjbvz** [comment]
Caused by a breaking change in the TS 2.6.2 API. Will fix upstream in https://github.com/Microsoft/typescript-template-language-service-decorator and pull in updated library downstream

**Comment by mjbvz** [comment]
Should be fixed in 0.2.2
