### ISSUE TITLE
No autocompletion in nested selectors

### ISSUE THREAD

**Issue by aczekajski** [Microsoft/typescript-styled-plugin#26]
In styled-components it is possible to nest the selectors, just like in SCSS, so you can write `&:hover { ... }` or `.wrapper & { ... }` or even `${OtherComponent} { ... }`. Unfortunately the autocompletion breaks inside the curly brackets.

When looking at this issue, I replaced the `this.cssLanguageService.doComplete` with `this.scssLanguageService.doComplete` in plugin source. Now, it can properly suggest css inside a nested selector. Downside of this solution is that now it also suggests all sort of SCSS functions which are not supported by the styled-components. Still better than having no autocomplete at all, but not enough to create a PR for that I guess.

I see two ways of resolving that problem. First: restrict the results returned from `scssLanguageService.doComplete` so they don't contain SCSS functions. Second: parse the code with SCSS and perform CSS version of `doComplete` only on the code part enclosed by current selector scope.

**Comment by aczekajski** [comment]
Version 0.3.0 doesn't introduce any improvement on that. Any other development?

**Comment by mjbvz** [comment]
Fixed by #27
