### ISSUE TITLE
ts-styled-plugin not respect the rules in stylelint.config.js

### ISSUE THREAD

**Issue by wangbourne** [Microsoft/typescript-styled-plugin#29]
My environment:
1. Visual Studio Code under Mac, Version 1.19.2 
2. "styled-components": "^2.4.0", 
3. "stylelint": "^8.4.0", 
4. "stylelint-config-standard": "^18.0.0", 
5. "stylelint-config-styled-components": "^0.1.1", 
6. "stylelint-processor-styled-components": "^1.2.1", 
7. "typescript": "^2.6.2", 
8. "typescript-styled-plugin": "^0.4.0"

`stylelint.config.js` is shown below with a rule of ignoreProperties: `resize-mode`
```
module.exports = {
  processors: ["stylelint-processor-styled-components"],
  extends: ["stylelint-config-standard", "stylelint-config-styled-components"],
  syntax: "scss",
  rules: {
    "property-no-unknown": [
      true,
      {
        ignoreProperties: ["/shadow/", "resize-mode"]
      }
    ]
  }
};
```

However, I still can see the error of "[ts-styled-plugin] Unknown property."
![image](https://user-images.githubusercontent.com/2090084/35125007-d6108a1e-fcf3-11e7-800d-4a1181e6b893.png)

**Comment by mjbvz** [comment]
Out of scope for this plugin.

You can disable built-in linting [as described here](https://github.com/Microsoft/typescript-styled-plugin#linting). You could also write a TS plugin that add stylelint based linting to styled blocks
