### ISSUE TITLE
Emmet suggestions do not use snippets 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/typescript-styled-plugin#36]
**Steps to reproduce**
1. For the code

    ```js
    import * as styled from 'styled-components'

    export const Button = styled.button`
        bdlw
    `
    ```

2. Trigger suggest on `bdlw `

**Expected**

```js
import * as styled from 'styled-components'

export const Button = styled.button`
    border-left-width: |;
`
```

Where `|` is the cursor

**Actual**

```js
import * as styled from 'styled-components'

export const Button = styled.button`
    border-left-width: ;|
`
```

**Comment by mjbvz** [comment]
Probably depends on https://github.com/Microsoft/TypeScript/issues/21999 as well

**Comment by iahu** [comment]
for me
```tsx
export const Button = styled.button`
    bdlw
`
```
will be
```tsx
export const Button = styled.button`
    <bdlw></bdlw>
`
```

what's the problem?

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
