### ISSUE TITLE
Document how to use plugin with regular Visual Studio

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/typescript-styled-plugin#4]
I believe Visual Studio supports TypeScript server plugins as well, but after installing the plugin and configuring my `tsconfig.json`, I did not see the plugin being activated

// cc @RyanCavanaugh

**Comment by RyanCavanaugh** [comment]
There's nothing special here AFAIK - the Angular2 plugin loads successfully in VS, for example. If you have a zip with your project I can try it out

**Comment by mjbvz** [comment]
Here's a zip of the project. I tried both using an NTVS template and using open folder in VS but didn't see the plugin being activated

[NodejsConsoleApp1.zip](https://github.com/Microsoft/typescript-styled-plugin/files/1370359/NodejsConsoleApp1.zip)

**Comment by RyanCavanaugh** [comment]
The server log indicates that your module doesn't load:
```
Info 10   [12:40:38.43] Failed to load module 'typescript-styled-plugin': SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (c:\users\ryanca\desktop\nodejsconsoleapp1\nodejsconsoleapp1\node_modules\typescript-styled-plugin\lib\index.js:8:50)
    at Module._compile (module.js:397:26)
```
The problem is this parameter destructuring in `template-string-language-service-proxy.js`:
```ts
    build(languageService) {
        const ret = languageService;
        this._wrappers.forEach(({ name, wrapper }) => {  <--------
            ret[name] = wrapper(languageService[name]);
        });
        return ret;
    }
```
The version of node bundled with VS is only 5.4.1 and doesn't support this syntax (there may be other problems like this present, but this is the first one I found). I'd recommend building your plugin with `--target ES5`.

**Comment by mjbvz** [comment]
Thanks for looking into this. I'll see about using an es5 target instead. How did you manage to collect the tsserver logs from VS? Just setting `TSS_LOG` in windows?

**Comment by mjbvz** [comment]
Added documentation. Requires 0.1.2+ of this plugin. I still don't see error reporting in the strings but will file a separate issue about that
