### ISSUE TITLE
Throws warning for valid style property resizeMode

### ISSUE THREAD

**Issue by duro** [Microsoft/typescript-styled-plugin#45]
On the image element, resizeMode (resize-mode) is a valid property, but I get a warning:

![style_tsx_ _freebirdnative](https://user-images.githubusercontent.com/17632/38347173-b2401cbc-384e-11e8-901d-8fd1005ec3a7.jpg)

However, this is a perfect valid property for the Image element.

**Comment by mjbvz** [comment]
I don't see this css property documented anywhere. Do you mean `resize`?

**Comment by duro** [comment]
It is specific to react-native.

**Comment by mjbvz** [comment]
Merging into #58
