### ISSUE TITLE
colon/semi-color expected error

### ISSUE THREAD

**Issue by bernatfortet** [Microsoft/typescript-styled-plugin#49]
![image](https://user-images.githubusercontent.com/390010/37116750-05d5a5a6-2204-11e8-8704-620d7e5b92f9.png)

When I import a literal string from one of my npm libraries it gives an error
`semi-color expected` and `colon-excpected`

I tried the same object structure but without module and it works fine.
![image](https://user-images.githubusercontent.com/390010/37116813-2acf2b2a-2204-11e8-9dbb-973808b957ef.png)

(As referenced from https://github.com/styled-components/vscode-styled-components/issues/67)

**Comment by mjbvz** [comment]
I believe this is fixed in 0.6.2: https://github.com/styled-components/vscode-styled-components/pull/80

**Comment by bernatfortet** [comment]
Nice!
But I guess the updated package hasn't been published?

**Comment by mjbvz** [comment]
It is published. Styled components just needs to pick it up too
