### ISSUE TITLE
emptyRules throws warning on expressions

### ISSUE THREAD

**Issue by Wavum** [Microsoft/typescript-styled-plugin#50]
Example:
![image](https://user-images.githubusercontent.com/15262665/39370050-32754208-4a3e-11e8-816f-cb2fa0b547e5.png)

I don't think this should be a valid warning.

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by Wavum** [comment]
```js
const test = css`
    :nth-of-type(1) {
        ${true ? "display: initial" : "display: hidden"}
    }
`;
```

**Comment by mjbvz** [comment]
This appears to have been fixed at some point. Added test and closing
