### ISSUE TITLE
} expected for @-moz-document url-prefix()

### ISSUE THREAD

**Issue by Robbilie** [microsoft/typescript-styled-plugin#51]
https://i.imgur.com/sWpIzvc.png

```
const StyledTabNavigationWrapper = styled.div`
  position: relative;
  overflow-x: hidden;

  @-moz-document url-prefix() {
    max-height: 32px;
    overflow-y: hidden;
  }
`;
```

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
