### ISSUE TITLE
[ts-styled-plugin] colon expected

### ISSUE THREAD

**Issue by ApacheEx** [Microsoft/typescript-styled-plugin#54]
I noticed a bug recently. I got an error like this:
![image](https://user-images.githubusercontent.com/1918108/40176614-a509bd16-59e4-11e8-861f-f1d5c219a22c.png)

The code is available here: https://gist.github.com/ApacheEx/e1242d762a3fc98926d1605f1e8c6e77

My Environment:
- **Editor**: VSCode 1.23.1
- **Extension**: vscode-styled-components 0.0.18
- **OS**: macOS Hight Sierra 10.13.4

**Comment by joaopedrodcf** [comment]
I have a similar problem maybe is related, it happens in styled-components as well
![problem](https://user-images.githubusercontent.com/11476152/40396079-0c79b3c4-5e23-11e8-999c-9c9593140b1f.png)

**Comment by Undistraction** [comment]
![cap](https://user-images.githubusercontent.com/161489/40992197-0be1c30e-68ee-11e8-8272-95b24cb10dcc.jpg)

Another example when using styled-components:

> [ts-styled-plugin] colon expected

**Comment by mjbvz** [comment]
Here's the code that controls this: https://github.com/Microsoft/typescript-styled-plugin/blob/f82699d1a0027cb850118adfcdd8cf88203573dc/src/index.ts#L20

And steps to contribute: https://github.com/Microsoft/typescript-styled-plugin#contributing
