### ISSUE TITLE
IntelliSense doesn't work with emotion-style TypeScript declarations

### ISSUE THREAD

**Issue by nicolasschabram** [Microsoft/typescript-styled-plugin#56]
Hey guys,

using [vscode-styled-components](https://github.com/styled-components/vscode-styled-components) I noticed that linting and IntelliSense aren't quite working for me when providing TypeScript declarations to a styled react-emotion component. I've already [reported an issue](https://github.com/styled-components/vscode-styled-components/issues/92), but was sent here for the IntelliSense part.

![linting](https://user-images.githubusercontent.com/1027642/40853708-585b39d0-65cf-11e8-8ce1-eb1226eda96f.PNG)

Do you have an idea for how to fix this?

Thanks a lot for your help!
Nicolas

**Comment by Jonjoe** [comment]
+1 on this. Having the same issues.

**Comment by kachkaev** [comment]
A couple of other non-working examples by @umlx5h (https://github.com/styled-components/vscode-styled-components/issues/92#issuecomment-394045996):

![code](https://user-images.githubusercontent.com/20206121/40868830-48deec5e-664c-11e8-8662-85c58be623a1.png)

One more syntax flavour to support in future:

```ts
const Title = styled.h1<{ size: number }>`
  font-size: ${p => p.size}em;
`
```

ref: https://github.com/styled-components/styled-components/pull/1798

**Comment by nicolasschabram** [comment]
Thanks a lot for fixing this, @mjbvz! I just discovered that emotion has recently changed their TS definitions. Apparently, you can now do something like this:

```tsx
const MyComponent = styled('div')<Props>`
  color: ${props => props.color};
`:
```

Is that case covered by your changes, too?

**Comment by mjbvz** [comment]
Yes (but syntax highlighting may still not work)

**Comment by DJWassink** [comment]
Can confirm that syntax highlighting isn't working on the latest version with those 2 cases:
![image](https://user-images.githubusercontent.com/1822404/42263746-38ec7348-7f6f-11e8-80c7-31d450110e1b.png)

Is there some place we can follow the progress on these cases? 

Thanks a ton for the hard work on this plugin!

**Comment by slater101** [comment]
Is it possible to turn off the linting for this? I get littered with false errors from the linter, turning it off would make my day. 

`export const themeProp = (themeProp) => {
    return props => props.theme[themeProp];
};`

and I am just calling the function like so:
`${themeProp('colorLightOrange1')`

( I like to read it this way vs typing out the props, and this causes TONS of linting issues. )

Tried 
`"typescript-styled-plugin": {
        "validate": false
    }`

In vscode but no such configuration setting.
The only problem I seem to see with this plugin is the linter, yet I see no way to de-activate it.
