### ISSUE TITLE
[ts-styled-plugin] } expected

### ISSUE THREAD

**Issue by DJWassink** [Microsoft/typescript-styled-plugin#59]
Making a selector for multiple other components currently shows an syntax error (while it should be correct)

![image](https://user-images.githubusercontent.com/1822404/41276579-ea9333cc-6e24-11e8-8c96-d919c2308a7c.png)

Minimal code to reproduce:
```js
const Child1 = styled.div``;
const Child2 = styled.div``;
const Container = styled.div`
    ${Child1}, ${Child2} {}
`;
```

My Environment:
Editor: VSCode 1.24.0
Extension: vscode-styled-components 0.0.18
OS: Windows 10

**Comment by mjbvz** [comment]
Here's the code that controls this: https://github.com/Microsoft/typescript-styled-plugin/blob/f82699d1a0027cb850118adfcdd8cf88203573dc/src/index.ts#L20

And steps to contribute: https://github.com/Microsoft/typescript-styled-plugin#contributing
