### ISSUE TITLE
Breaks when adding prop type to styled component

### ISSUE THREAD

**Issue by simonacca** [Microsoft/typescript-styled-plugin#63]
```
interface Props {
  open: boolean
}

const Wrapper = styled.div<Props>`
  border: 1px solid ${(props) => (props.open ? 'blue' : 'transparent')};
  border-
`
```

### Expected behaviour

Placing the cursor after `border-` presents border css properties.

### Actual behaviour

No intellisense suggestions are presented.

## Additional notes
When `<Props>` is removed, the plugin works as expected and intellisense suggestions are shown.

# Versions

* Vscode: 1.24.1 (24f62626b222e9a8313213fb64b10d741a326288) x64
* typescript: (workspace) 2.9.2
* styled-components: 3.3.3
* typescript-styled-plugin: 0.10.0

**Comment by mjbvz** [comment]
IntelliSense seems to work. Try manually requesting completions with ctrl+space. It's just that the syntax highlighting doesn't work, see: https://github.com/styled-components/vscode-styled-components/issues/114
