### ISSUE TITLE
Syntax error (colon expected) with style attribute (in html template literal)

### ISSUE THREAD

**Issue by ncodefun** [Microsoft/typescript-styled-plugin#64]
I'm reporting this here since it's this plugin that reports the error, but the context is that I work with lit-html and the vscode-lit-html extension ... So I have this:
![ts-styled-error](https://user-images.githubusercontent.com/35607086/42738591-2d6f804e-8854-11e8-9878-7bcc4fad6db9.png)

This only happens with the style attribute, and **only when the template string is multi-line**.  Tried with other styles before or after the expression and it doesn't work either (I thought maybe it looks for at least one colon/semi-colon pair).

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/typescript-lit-html-plugin#19
