### ISSUE TITLE
Proposal: add support for custom function calls

### ISSUE THREAD

**Issue by acrazing** [Microsoft/typescript-styled-plugin#68]
For example, the [styled decorator](https://github.com/styled-components/styled-components/issues/537#issuecomment-305466183).

It could be called in the form:

```ts
@withStyles`
  color: #f00;
`
export class Foo extends PureComponent {
}
```

**Comment by mjbvz** [comment]
Try configuring [`tags`](https://github.com/Microsoft/typescript-styled-plugin#tags) in your jsconfig or tsconfig:

```json
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "typescript-styled-plugin",
        "tags": [
          "withStyles",
          "css",
          "styled"
        ]
      }
    ]
  }
}
```
