### ISSUE TITLE
Support for "disable next line check"

### ISSUE THREAD

**Issue by hen42** [Microsoft/typescript-styled-plugin#70]
Hi all, great tool!

I am Using VS code 1.26.1

In  a typescript file I have code like this

const Css = html`
 <style>
          <br>
           /*  would like to disable the ts-styled-plugin check for the next line */

         <br>
          bla bla bla 
         <br>

  </style>`;    
<br>

  It would be cool to have ts-styled plugin not check the line with the text "bla bla bla".

Is it possible to have something like   /* ts-styled-plugin:disable-next-line */  which will disable the check ?
Thanks

**Comment by mjbvz** [comment]
Out of scope for this extension. You can disable validation entirely however as described here: https://github.com/Microsoft/typescript-styled-plugin#linting

**Comment by sbusch** [comment]
@hen42 why is this out of scope?

**Comment by hen42** [comment]
@sbusch , I don't know why this out of scope. I thought it would be nice to have this feature, because other tools like 'lint tools' have the some option to disable next line check.

**Comment by nicholaai** [comment]
this definitely should be supported. how is this out of scope, @mjbvz? 

disabling the whole plugin makes no sense. for instance, i have an issue where i need to add a vendor prefix css rule for IE11 only. 

```
-ms-height: ${({ height }) => `${height}.1px`};
```

any other browser will use my utility method to set height based off of what i pass as a prop. i don't want to write a `height:` rule, yet i'm being yelled at. 

seems like others have similar issues. thoughts?

**Comment by sbusch** [comment]
Sorry @hen42 I rather wanted to ping @mjbvz

**Comment by madeleineostoja** [comment]
Also don't see why this is out of scope, pretty common feature for linting tools and extensions. Is it because of technical limitations?

**Comment by lanwin** [comment]
@mjbvz I also dont understand why this is out of scope. We work with a product called PDF-Reactor that implements basically DOM to PDF. They added some third party CSS selectors to control page properties. 

It would be very helpful to disable linting only for the next line to ignore only these extension and not anything else. This is also like the other linting Plugins work.

**Comment by MauriceNino** [comment]
We are working with react-native-paper and one of its custom style properties (`elevation`) does not get recognized. That would be ok, if I could just disable to check for this line, or add custom properties.

```tsx
const MainSurface = styled(Surface)`
  elevation: 2;
`;
```

**Comment by btonasse** [comment]
This should not be closed
