### ISSUE TITLE
`ts-styled-plugin` error on valid referred component template literal curly brace

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/typescript-styled-plugin#74]
_From @awwong1 on July 13, 2018 22:55_

Hello, I'm seeing `ts-styled-plugin` errors while using this plugin (version `0.0.21`) and referred components in my application.

I have verified that my code compiles and renders in the browser without issues.

I see the following errors around the two curly braces after the referred component selector.
```typescript
const ListNoteTitle = styled.span`
  font-weight: bold;
  color: ${props => props.theme.primaryColor};
  ${ListNoteItem}:hover & {
    text-decoration: underline;
  }
`;
```
![screenshot from 2018-07-13 16-49-20](https://user-images.githubusercontent.com/2760111/42717230-c788e3b2-86bc-11e8-9f75-df0bba6c9147.png)

*  `[ts-styled-plugin] semi-colon expected` on the first curly brace
* `[ts-styled-plugin] at-rule or selector expected` on the second curly brace

I think this is a plugin issue. My relevant source code can be found here:
* [View Component](https://github.com/udia-software/udia-client/blob/c01b4c5d3219e350b6392788c1274f5dc7f3a0c5/src/Components/Notes/ListNotesView.tsx#L41)
* [Styled Theme](https://github.com/udia-software/udia-client/blob/c01b4c5d3219e350b6392788c1274f5dc7f3a0c5/src/Components/AppStyles.ts)

_Copied from original issue: styled-components/vscode-styled-components#117_

**Comment by mjbvz** [comment]
_From @leemun1 on August 27, 2018 15:40_

I got this issue too while trying to refer to a different styled component.
Did this get fixed yet?

```javascript
const SomeStyledComponent = styled.div`
  background: red;
${SomeOtherStyledComponent}:hover & { // error on the curly braces from this line
  background: blue;
} // and here
`
```

**Comment by mjbvz** [comment]
_From @olhapi on September 17, 2018 14:46_

Still have this issue, but only on opening brace.
![screen shot 2018-09-17 at 17 35 11](https://user-images.githubusercontent.com/4780263/45630503-7fb6fd80-baa1-11e8-8ccd-556b43a02bfe.png)

**Comment by nmaves** [comment]
I am also getting this with the following.

<img width="946" alt="card_js_ _www-ecommerce_and_meaves-www_ _-bash_ _146x43" src="https://user-images.githubusercontent.com/367750/45713309-eabd0e80-bb4b-11e8-9c54-0812c206f5d6.png">

**Comment by akc42** [comment]
I just upgraded to September edition of vscode (on linux) and now get this too

![screenshot from 2018-10-13 16-26-14](https://user-images.githubusercontent.com/368238/46907270-f829a680-cf07-11e8-99c6-b6c13d65128d.png)

the second problem at the bottom says semi-colon expected.

**Comment by bernatfortet** [comment]
Any updates on this issue? It's been happening to me since August

**Comment by mjbvz** [comment]
Original issue is fixed as far as I can tell:

![screen shot 2018-11-08 at 3 58 07 pm](https://user-images.githubusercontent.com/12821956/48234633-2a93bb80-e36f-11e8-89af-e893de880e00.png)

If you still see an error, please open a new issue for your specific case. Include your code as text (not screenshots)

**Comment by mjbvz** [comment]
Actually still hit this in some cases with original example

**Comment by kylemh** [comment]
Excited to see https://github.com/Microsoft/typescript-styled-plugin/commit/b17aa81653a1afe4e3dca0717757f5e0487001d7

👍 ty for your hard work

**Comment by protoEvangelion** [comment]
@mjbvz Still getting this in a similar example:

```js
<Component animation={css`${condition ? animation1 : animation2} 1s linear`} />
```
![image](https://user-images.githubusercontent.com/20076677/48307460-d5d47a00-e501-11e8-87ef-4ca5f30c3deb.png)

![image](https://user-images.githubusercontent.com/20076677/48307463-e258d280-e501-11e8-9dff-52dd60df374f.png)

**Comment by mjbvz** [comment]
Open a new issue

**Comment by wangpin34** [comment]
To me, a similar issue was resolved by disabling another plugin: [styled-jsx Language Server](https://marketplace.visualstudio.com/items?itemName=AndrewRazumovsky.vscode-styled-jsx-languageserver)

**Comment by ricardobossan** [comment]
https://gitmemory.com/issue/microsoft/typescript-styled-plugin/100/572014717 this solved it for me.

**Comment by HypeNeutron** [comment]
> 
> 
> Original issue is fixed as far as I can tell:
> 
> ![screen shot 2018-11-08 at 3 58 07 pm](https://user-images.githubusercontent.com/12821956/48234633-2a93bb80-e36f-11e8-89af-e893de880e00.png)
> 
> If you still see an error, please open a new issue for your specific case. Include your code as text (not screenshots)

But How?
