### ISSUE TITLE
Closing tag autocompletion is missing '>'

### ISSUE THREAD

**Issue by jolleekin** [Microsoft/typescript-styled-plugin#76]
## Steps to reproduce
1. Type `<some-tag></`

## Actual
- The plugin suggests `/some-tag`

## Expected
- The plugin suggest `/some-tag>`

## Suggestions
Even better, the plugin could automatically insert the closing tag when user finishes typing the opening tag. For example, the plugin automatically inserts `</some-tag>` after user types `<some-tag>` or `<some-tag attribute1="value1" attribute2="value2">`.

**Comment by mjbvz** [comment]
I think you have the wrong repo. This one is for styled components
