### ISSUE TITLE
"@-ms-viewport" error "expected (css-rcurlyexpected)"

### ISSUE THREAD

**Issue by heart-of-code** [microsoft/typescript-styled-plugin#77]
Shows an error for "@viewport" and "@-ms-viewport"

I'm trying to use @-ms-viewport because IE10 ignores the viewport metadata when it's snapped

![the culprit](https://user-images.githubusercontent.com/8591101/46265437-a59dc280-c4e3-11e8-8330-d1adf59a0383.PNG)

**Comment by afshin-hoseini** [comment]
@heart-of-code How did you solve it?

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
