### ISSUE TITLE
Plugin breaks intellisense

### ISSUE THREAD

**Issue by asvetliakov** [Microsoft/typescript-styled-plugin#78]
Enabling plugin / installing ```vscode-styled-components``` extensions (which uses this plugin) results into this issue:

![gif](http://g.recordit.co/BWzeKn0e02.gif)

[video version here](http://recordit.co/BWzeKn0e02)

I think the gif is self-explained - TS returns global completion instead of ```x, z```

I thought it was TS issue initially and filed [this bug](https://github.com/Microsoft/TypeScript/issues/27529) in TS repo first, but looks like it's completely related to this plugin

**Comment by asvetliakov** [comment]
Workaround:

Replace ```node_modules/typescript-styled-plugin/lib/index.js``` with following:

```js
"use strict";
var decorator = require("typescript-template-language-service-decorator/lib/template-language-service-decorator");
// disable getOutliningSpans, this is causing problem
decorator.default.prototype.tryAdaptGetOutliningSpans = function () { }
var _plugin_1 = require("./_plugin");
module.exports = function (mod) {
    return new _plugin_1.StyledPlugin(mod.typescript);
};
```

The problem that editor sends ```getOutliningSpans``` on every keystroke and template decorator enumerate all nodes in the sourcefile each time, i'm assuming this should be pretty slow (Does TS do any locking of program/source file? copying? - this would explain the stale diagnostic)

**Comment by gaoxiaoliangz** [comment]
Why closing this issue? Has this been fixed?
