### ISSUE TITLE
Can't use it in the vscode workspace

### ISSUE THREAD

**Issue by MrKou47** [Microsoft/typescript-styled-plugin#79]
I want to use this plugin in the workspace.Here is what i do.

env:

- macOS majove
- typescript 3.1.6
- vscode 1.28.2

- create an empty folder named 'my-project'
- npm init -f
- yarn add typescipt typescript-styled-plugin
- create a tsconfig.json
- Select typescript version - workspace version
- write some code in `my-project/index.js`
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true,
    "plugins": [
      {
        "name": "typescript-styled-plugin",
      }
    ]
  }
}
```

set vscode `"typescript.tsserver.trace": "verbose"`

![demo](https://image.ibb.co/fudCSq/tsplugin.gif)

And you can see the `typescript-styled-plugin` still doesn't work.

**Comment by mjbvz** [comment]
@MrKou47 Have you tried manually triggering intellisense? It will only automatically trigger if you have the VS Code styled extensions installed (which also adds syntax highlighting)

**Comment by MrKou47** [comment]
@mjbvz thanks for your reply.I had installed *VS Code Styled Components extension* and it works fine.
But when i read the [doc](https://github.com/Microsoft/typescript-styled-plugin/blob/e45ca1adcccbaa9fa75a59a184b6dc52722598c9/README.md#with-vs-code) i think it can be triggered when i make the right config.Maybe we should update the README?

**Comment by mjbvz** [comment]
If there is no syntax highlighting, intellisense on type does not work as expected. Please file an [upstream issue](https://github.com/styled-components/vscode-styled-components) about the lack of highlighting
