### ISSUE TITLE
@page is marked as an error

### ISSUE THREAD

**Issue by dusanjovanov** [microsoft/typescript-styled-plugin#83]
I get an error with the @page selector in this code: 

![capture](https://user-images.githubusercontent.com/20474783/48675337-02b70b80-eb58-11e8-9058-bb869dca6be3.PNG)

And these are the errors:

![capture2](https://user-images.githubusercontent.com/20474783/48675347-1f534380-eb58-11e8-9daa-136c4c38abf4.PNG)

I don't have a problem with any other code

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
