### ISSUE TITLE
Plugin complain when using the label property for Emotion

### ISSUE THREAD

**Issue by carpben** [Microsoft/typescript-styled-plugin#84]
The label property is used by 'Emotion.js' to customize the name of the rendered css class. The plugin doesn't recognize it as a legimtimate property and complains. 
![image](https://user-images.githubusercontent.com/13496178/49026580-e134d000-f1a6-11e8-9237-635a3fd2eb51.png)

**Comment by mjbvz** [comment]
Since this is a non-standard property, use the `validProperties` linter setting for this:

```
        "plugins": [
            {
                "name": "typescript-styled-plugin",
                "lint": {
                    "validProperties": [
                        "label"
                    ]
                }
            }
        ]
}
```

**Comment by carpben** [comment]
What file should I insert this json to?

**Comment by carpben** [comment]
Found the answer - tsconfig.json

**Comment by robinmetral** [comment]
Hi @carpben, did this fix it for you? I'm still getting the issue.

According to [emotion/issues/1037](https://github.com/emotion-js/emotion/issues/1037), `tsconfig.json` should actually look like this, with `plugins` under `compilerOptions`:

```json
{
  "compilerOptions": {
    "plugins": [
      {
        "name": "typescript-styled-plugin",
        "lint": {
          "validProperties": "label"
        }
      }
    ]
  }
}
```

@mjbvz do I need anything else in `tsconfig.json` for this to work? Also I should mention that I'm not actually using typescript in that project, not sure if this changes anything.

Thank zou!

**Comment by carpben** [comment]
@robinmetral Since then I stopeed using labels, so unfortunately I can't help with that.

**Comment by robinmetral** [comment]
No worries, thanks @carpben
