### ISSUE TITLE
Syntax highlighting is disabled when used typescripts types in vscode

### ISSUE THREAD

**Issue by Dudeonyx** [Microsoft/typescript-styled-plugin#86]
Vscode: 1.29.1
Typescript:
![image](https://user-images.githubusercontent.com/23441172/49691520-417f2680-fb44-11e8-8780-b016b6c4ebc3.png)

Without types it works fine but typescript complains if i try to pass or use props

![image](https://user-images.githubusercontent.com/23441172/49691482-b9991c80-fb43-11e8-8c78-71a830870318.png)

With types

![image](https://user-images.githubusercontent.com/23441172/49691469-60c98400-fb43-11e8-8366-a81a44fd0682.png)

IntelliSense and other features still work, but no highlighting

**Comment by Dudeonyx** [comment]
But this works 

![image](https://user-images.githubusercontent.com/23441172/49691658-c0299300-fb47-11e8-8cbf-67e8c2262a87.png)

and allows me to pass the open prop.

eg.   `<StyledSideDrawer open={true} />`

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by mjbvz** [comment]
This repo doesn't provide syntax highlighting. Upstream issue: https://github.com/styled-components/vscode-styled-components/issues/81
