### ISSUE TITLE
Unrecognized property `place-self`

### ISSUE THREAD

**Issue by aryzing** [Microsoft/typescript-styled-plugin#87]
The shorthand property `place-self` (used on a grid item) is not recognized:

```
Unknown property: 'place-self'
```

**Comment by mjbvz** [comment]
Upstream issue: https://github.com/Microsoft/vscode/issues/64835

**Comment by apust** [comment]
https://github.com/mdn/data/issues/253 is fixed and [adopted ](https://github.com/microsoft/vscode-css-languageservice/commit/13967584effb3e9c07ec1e827146dedf35f32703) in vscode-css-languageservice@4.0.2.

Can we upgrade to 4.0.2 from 3.0.13?
