### ISSUE TITLE
Template literal with curly brace and newline triggers a 'semi-colon expected' error

### ISSUE THREAD

**Issue by phucanhapril** [microsoft/typescript-styled-plugin#88]
Verified that code compiles and renders in the browser with no issues.

I'm using multiple embedded strings in a template literal for the `transition` property, and the plugin has no problem when everything is on the same line:
<img width="614" alt="screen shot 2018-12-17 at 1 40 00 am" src="https://user-images.githubusercontent.com/6667278/50070705-10829f80-019d-11e9-8ce6-7f426b6de36a.png">

My code formatter automatically transforms the string to take up two lines, and that's when I get errors (on lines 91 and 93):
<img width="408" alt="screen shot 2018-12-17 at 1 40 35 am" src="https://user-images.githubusercontent.com/6667278/50070732-2a23e700-019d-11e9-86b6-d7b67feaaef0.png">

<img width="350" alt="screen shot 2018-12-17 at 1 40 55 am" src="https://user-images.githubusercontent.com/6667278/50070750-38720300-019d-11e9-8803-b36739908e6c.png">

Possibly related to [#74](https://github.com/Microsoft/typescript-styled-plugin/issues/74) and [#71](https://github.com/Microsoft/typescript-styled-plugin/issues/71)

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by phucanhapril** [comment]
screenshots of code and errors are in the original description, transcribing the most relevant code below:

this is fine
```js
transition: padding-left ${theme.animation.transitionDuration} ${theme.animation.transitionTiming};
```

but that's a long line so it gets formatted to this, which triggers errors:
```js
transition: padding-left ${theme.animation.transitionDuration} // semi-colon expected
  ${theme.animation.transitionTiming}; // at-rule or selector expected
```

**Comment by mmirus** [comment]
Running into this as well:

```ts
padding: ${props => props.theme.remScale[2]}
    ${props => props.theme.remScale[3]};
```

**Comment by Hannes-Sandahl-Mpya** [comment]
I'm also having this issue. Se attached example.
![Screenshot 2019-03-13 at 09 15 51](https://user-images.githubusercontent.com/45267496/54263247-b06b8180-4570-11e9-9a6a-2e475ff63c9d.png)

**Comment by Kjagd** [comment]
This is happening for me with the default prettier settings. 
[Prettier playground example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBRAHgQwFsAHAGzkwF5MMBPcgEwDoGBLANwAMAdKTfzMXwM2UAOZJMAEmDEAThGJoqAPkEKlTGAAs4hOE3zk5MAArDRYgBoBfabI3LKa+YrRbd+w8bMXW4gE0bAG5eTlCoEAAaEEUYVnRkUHw5BQB3czkENGQQfHYIVgZokAAjOXwwAGs4GABlITB-MWQYOQBXOBjtGEJSAHVtVng0Rrg67OGOYdpcsDQcmP80OBNTCrFCfGQAMyMVmIArNFwAIQrq2rqiOAAZfzhd-a6QY9w65vIARXaIeCfSAcQEI5Cs5LlSvhSvRoCVXCt+hViLl5HAwexHjEsgBHdqsLLrfCbbZIPaAl4rQisVodCmfOA-P6PUnPGIwKH9Io6ZAAJjZFVYpGaAGEIIQtrkoNBMSB2isACpQnIs8kxfAYAFAhgQMCal4QdowYiGnl6mLyfwwTkMblIAAcAAYbDYgA)

**Comment by MaxMcKinney** [comment]
I also am having this issue, prettier settings cause a newline to be created and this gives me the same errors. Any progress on this issue?

**Comment by karlhorky** [comment]
Also seeing this problem with prettier and CSS template strings using `createGlobalStyle` from `styled-components`:

![Screen Shot 2019-10-19 at 08 24 57](https://user-images.githubusercontent.com/1935696/67138894-4162b380-f24a-11e9-9967-a8f2b9a7da5b.png)

```js
import { createGlobalStyle, ThemeProvider } from 'styled-components';

const GlobalStyle = createGlobalStyle`
  @font-face {
    font-family: 'Averta Standard';
    font-weight: 800;
    font-style: normal;
    font-display: swap;
    src: local('☺'),
      url('${
        process.env.PUBLIC_URL
      }/averta-standard-extra-bold.woff2') format('woff2');
  }
```

**Comment by karlhorky** [comment]
Hm, reading this a bit more, I'm thinking that this may be unrelated.

@mjbvz what's your read on this? Should I open a new issue for my problem?

**Comment by refactorized** [comment]
> Hm, reading this a bit more, I'm thinking that this may a slightly different issue.
> 
> @mjbvz what's your read on this? Should I open a new issue for my problem?

Looks similar to
https://github.com/microsoft/typescript-styled-plugin/issues/100

**Comment by karlhorky** [comment]
@refactorized Thanks for the tip! Commented over there too :)

**Comment by snehalbaghel** [comment]
I'm not sure if it's related to this issue but I get these false positives:

![image](https://user-images.githubusercontent.com/17233313/96376934-7710e400-119f-11eb-973c-3fb6f5669bae.png)

What causes the error:

```typescript
const StyledBubble = styled.div`
  ${(props) =>
    props.left
      ? 'border-bottom-left-radius'
      : 'border-bottom-right-radius'}: 0px;
`;
```

What works (remove the newlines):

```typescript
const StyledBubble = styled.div`
   ${(props) => props.left ? 'border-bottom-left-radius : 'border-bottom-right-radius'}: 0px;
`;
```

**Comment by snehalbaghel** [comment]
@mjbvz If you can point me to where the fix needs to be done I can make a PR.

**Comment by NTag** [comment]
Running into this too:
```js
padding: ${({ theme }) => theme.spacings.abs4}
  ${({ theme }) => theme.spacings.abs8};
```
This is a valid syntax and shouldn't trigger an error:
<img width="424" alt="CleanShot 2020-10-31 at 20 25 12@2x" src="https://user-images.githubusercontent.com/906276/97788173-352c6880-1bb7-11eb-83d7-ab2ac7902a49.png">

**Comment by stanislawdera** [comment]
I'm getting the same issue now. Is that related?

```js
export const Wrapper = styled.div`
  background-color: red;

  div {
    padding: ${({ theme }) => theme.spacing.md}
      ${({ theme }) => theme.spacing.sm};
  }
`
```
When I remove the newline everything starts working:
```js
padding: ${({ theme }) => theme.spacing.md} ${({ theme }) => theme.spacing.sm}; // works
```
```js
// produces error
padding: ${({ theme }) => theme.spacing.md}
  ${({ theme }) => theme.spacing.sm};
```

**Comment by stanislawdera** [comment]
I'm getting the same issue now. Is that related?

```js
export const Wrapper = styled.div`
  background-color: red;

  div {
    padding: ${({ theme }) => theme.spacing.md}
      ${({ theme }) => theme.spacing.sm};
  }
`
```
When I remove the newline everything starts working:
```js
padding: ${({ theme }) => theme.spacing.md} ${({ theme }) => theme.spacing.sm}; // works
```
```js
// produces error
padding: ${({ theme }) => theme.spacing.md}
  ${({ theme }) => theme.spacing.sm};
```

Is there any way to fix it (after 2 years since last comment on this issue)?

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
