### ISSUE TITLE
Template literal with multiline props lambda in a placeholder triggers errors

### ISSUE THREAD

**Issue by petmat** [microsoft/typescript-styled-plugin#89]
The following syntax in a styled component template literal triggers errors that it shouldn't:

![image](https://user-images.githubusercontent.com/3600035/50216798-6fa80600-038f-11e9-9a6b-703274a3e7c2.png)

Errors are `) expected` and `semi-colon expected`.

This is possibly related to #88 #74 and #71

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by petmat** [comment]
I'm not sure if this is a bug in typescript-styled-plugin or the https://github.com/styled-components/vscode-styled-components repo, but here is a repo with an example that repros the bug:

https://github.com/petmat/styled-plugin-bug

And here's the code from App.js:
```js
import React, { Component } from 'react';
import styled, { css, ThemeProvider } from 'styled-components';
import logo from './logo.svg';
import './App.css';

const ClickableIcon = css`
  cursor: pointer;
`;

const ClickableTreeIcon = css`
  ${ClickableIcon}

  width: 32px;
  height: 32px;
  background-image: url('${props => props.theme.paths.imgPath}/tree/tree.png');
`;

const MyIcon = styled.i`
  ${ClickableTreeIcon}
`;

const theme = {
  paths: { imgPath: '/imgs' }
};

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
          <ThemeProvider theme={theme}>
            <MyIcon />
          </ThemeProvider>
        </header>
      </div>
    );
  }
}

export default App;
```

Hope it helps!

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
