### ISSUE TITLE
Enabling global code-snippets

### ISSUE THREAD

**Issue by JDansercoer** [Microsoft/typescript-styled-plugin#90]
When I'm in a template literal, I'm unable to use my user-defined snippets. Is this an error on my end or did I forget to enable/disable something?

The reason for needing my snippets in the literals, is for an easy completion of elements that use props/theme values, e.g. this snippet

`${props => props.theme.$1}`

**Comment by mjbvz** [comment]
Where exactly are you trying to trigger the snippets? Please share some example code to explain

**Comment by mjbvz** [comment]
Closing as this needs more info
