### ISSUE TITLE
Add user-drag css option to plugin.

### ISSUE THREAD

**Issue by ZiiMakc** [microsoft/typescript-styled-plugin#91]
Can you please add user-drag css option to plugin, so it will not show an error?

I use it like this:
```
  a {
    user-drag: none; 
  }
```

It's works in chrome and safari as i know.

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
