### ISSUE TITLE
Automatically configure for workspace typescript version

### ISSUE THREAD

**Issue by esetnik** [Microsoft/typescript-styled-plugin#96]
I see that the https://github.com/Microsoft/vscode-typescript-tslint-plugin automatically configures itself to use a locally installed version of typescript:

> This extension works using VS Code's built-in version of TypeScript and a local or global install of tslint. You do not need to configure the plugin in your tsconfig.json if you are using VS Code's version of TypeScript.

> If you are using VS Code 1.30 or older and are using a workspace version of typescript, you must currently configure the TS Server plugin manually by following these instructions

Can this plugin do the same thing to avoid manual configuration on newer typescript versions?

**Comment by mjbvz** [comment]
No work should be required on the plugin side for this, but the extension that contributes the plugin needs to opt in this behavior. Here's an issue tracking that: https://github.com/styled-components/vscode-styled-components/issues/156
