### ISSUE TITLE
ts-styled-plugin(9999) ( expected

### ISSUE THREAD

**Issue by mantou132** [microsoft/typescript-styled-plugin#98]
```js
mediaQuery.PWA: '(display-mode: standalone)'
```
```js
html`
<style>
@media ${mediaQuery.PHONE} and ${mediaQuery.PWA} {}
</style>
`
```

<img width="489" alt="Screen Shot 2019-03-16 at 2 32 33 PM" src="https://user-images.githubusercontent.com/3841872/54471714-6399dc00-47f8-11e9-9fd5-bde2e2c08874.png">

Version 1.31.1 (1.31.1)

**Comment by edgarpiera** [comment]
![image](https://user-images.githubusercontent.com/10711509/71720965-b003e600-2e23-11ea-9507-e13194c3b35f.png)

**Comment by younessdev9** [comment]
I have the same issue here I'm  using style components
![Screenshot from 2021-02-15 14-13-54](https://user-images.githubusercontent.com/60606346/107951104-18fedc80-6f98-11eb-87e0-06193c009778.png)

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
