### ISSUE TITLE
Erroneous '{ expected' inside nested media query

### ISSUE THREAD

**Issue by maartenth** [microsoft/typescript-styled-plugin#99]
![Screenshot 2019-05-03 at 10 06 32](https://user-images.githubusercontent.com/298893/57125934-8d4c9980-6d8b-11e9-878d-2041eca3c7eb.png)
![Screenshot 2019-05-03 at 10 06 44](https://user-images.githubusercontent.com/298893/57125937-90478a00-6d8b-11e9-8b0f-9ff3be40eb8a.png)

**Comment by mjbvz** [comment]
Please share the text of the code along with screenshots

**Comment by DanielaValero** [comment]
Hello @mjbvz  I've got the same message, here an example of the code:

```
@supports (display: grid) {
    display: grid;
    grid-template-columns: 1fr;
    grid-template-rows: 1fr;
    grid-gap: 10px;

    @media screen and (min-width: 768px) {
      grid-template-rows: auto auto; --> In this line the error appears. 
    }
  }
```

When I move the second `@media` call to outside the nested block, the error does not appear.

**Comment by GLObus303** [comment]
Hi @mjbvz  

![image](https://user-images.githubusercontent.com/12488648/59961918-2d4ab780-94df-11e9-8cdb-59a1a5dd6eee.png)

Same here, same error, same line. Any update on this issue?

**Comment by andi1984** [comment]
Same for me on this constellation. I hope this is helpful.

![ts-styled](https://user-images.githubusercontent.com/1077917/66783466-3b7e7280-eed8-11e9-8921-7c4f9c2960d4.png)

**Comment by mjbvz** [comment]
Closing as this package has been deprecated in favor of the [official styled-components/typescript-styled-plugin fork]( https://github.com/styled-components/typescript-styled-plugin)

After updating to that fork, follow up in the styled-components repo if this is still an issue
